# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='icon_path',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='education',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='resume.Software'),
        ),
        migrations.AddField(
            model_name='software',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='resume.Experience'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='resume.Project'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.Education'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.Experience'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.Language'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.Project'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume.Software'),
        ),
    ]
