# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170423_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['the_order']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='certification',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='education',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='software',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
