# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20170423_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
