# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20170423_1812'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='language',
        #     name='id',
        # ),
        migrations.RemoveField(
            model_name='technology',
            name='education',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='language',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='software',
        ),
        migrations.AddField(
            model_name='education',
            name='technologies',
            field=models.ManyToManyField(to='resume.Technology'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(to='resume.Technology'),
        ),
        # migrations.AddField(
        #     model_name='language',
        #     name='technology',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resume.Technology'),
        # ),
        migrations.AddField(
            model_name='software',
            name='technologies',
            field=models.ManyToManyField(to='resume.Technology'),
        ),
    ]
