# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20170423_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='fakeColumn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
