# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20170423_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='language',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
