# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20170423_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='resume.Technology'),
        ),
        migrations.AlterField(
            model_name='education',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='resume.Technology'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='resume.Technology'),
        ),
        migrations.AlterField(
            model_name='software',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='resume.Technology'),
        ),
    ]
