# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20170423_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='github_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
